### ISSUE TITLE
Installing tabulizer

### ISSUE THREAD

**Issue by timspit** [ropenscilabs/tabulizer#21]
I'm pretty well stuck trying to install the package as described in the instructions. After installing chocolatey, then Java, then the ghit package, after running the code as laid out in the instructions:
**ghit::install_github(c("ropenscilabs/tabulizerjars", "ropenscilabs/tabulizer"), INSTALL_opts = "--no-multiarch")**
I get the following error:
**Error in build_and_insert(p$pkgname, d, vers, build_args, verbose = verbose) : 
  Package build for tabulizerjars failed!
In addition: Warning message:
running command '"C:/PROGRA~1/MIE74D~1/MRO-33~1.1/bin/x64/R" CMD build C:\Users\USERNAME\AppData\Local\Temp\Rtmp0mPJjx\tabulizerjars1cd83bee68cf ' had status 1** 

Any help troubleshooting would be very much appreciated.

**Comment by leeper** [comment]
Can you run it with `verbose = TRUE` and copy over the output?

**Comment by timspit** [comment]
Hi Thomas,

Thanks for your response. Ran with verbose = TRUE. Results as follows
(filepaths replaced in ALL CAPS):

Parsing reponame for 'ropenscilabs/tabulizerjars'...
Creating local git repository for tabulizerjars...
Checking out package tabulizerjars to local git repository...
[new]     627c0aa9800f10bc4d93 refs/remotes/github/master
Reading package metadata for 'ropenscilabs/tabulizerjars'...
Building package tabulizerjars...
'LOCAL FILEPATH FOR WORKING DOCUMENTS'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* checking for file
'C:\Users\USERNAME\AppData\Local\Temp\Rtmp0mPJjx\tabulizerjars1cd8103c72d6/DESCRIPTION'
... OK
* preparing 'tabulizerjars':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'tabulizerjars_0.1.2.tar.gz'
Warning in gzfile(tarfile, "wb", compression = compression_level) :
  cannot open compressed file 'C:/Windows/tabulizerjars_0.1.2.tar.gz',
probable reason 'Permission denied'
Error in gzfile(tarfile, "wb", compression = compression_level) :
  cannot open the connection
Execution halted
Error in build_and_insert(p$pkgname, d, vers, build_args, verbose =
verbose) :
  Package build for tabulizerjars failed!
In addition: Warning message:
running command '"C:/PROGRA~1/MIE74D~1/MRO-33~1.1/bin/x64/R" CMD build
C:\Users\USERNAME\AppData\Local\Temp\Rtmp0mPJjx\tabulizerjars1cd8103c72d6 '
had status 1

On Mon, Sep 12, 2016 at 12:38 PM, Thomas J. Leeper <notifications@github.com

**Comment by leeper** [comment]
Looks like a Windows permissions problem. Can you run R as an administrator?

**Comment by timspit** [comment]
That did it. Thanks for your help!

**Comment by leeper** [comment]
Great!
