### ISSUE TITLE
"Tabulizer not available for R 3.3.2"

### ISSUE THREAD

**Issue by Javs42** [ropenscilabs/tabulizer#28]
Attempted to run through the [tutorial](http://datascienceplus.com/extracting-tables-from-pdfs-in-r-using-the-tabulizer-package/) given on DataSciencePlus.com and went to install the Tabulizer package and the R console throws up the following warning: 

`> install.packages("tabulizer")`
`Warning in install.packages :
  package ‘tabulizer’ is not available (for R version 3.3.2)`

I did not see any open issues or discussion on the development page regarding this and wanted to bring it to the attention of the maintainers. 

Please let me know if you all have any further questions
Javier - javier.ignacio.alonso (at) gmail dot com

**Comment by sckott** [comment]
It's not on CRAN yet, see https://github.com/ropenscilabs/tabulizer#installation
